apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: msheaffer
  labels:
    app: db
spec:
  replicas: <REPLICAS>
  strategy:
    type: ClusterIP
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/msheaffer-harbor-project/db:971c881-1835277
        ports:
        - containerPort: 5432
